import type { ReportDefinition, StockReportCategory } from "./types";

const PRODUCT_FILTERS = [
  { key: "from", label: "From", type: "date-range" as const },
  { key: "to", label: "To", type: "date-range" as const },
  { key: "warehouseId", label: "Warehouse", type: "select" as const, optionsFrom: "warehouses" as const },
  { key: "locationId", label: "Location", type: "select" as const, optionsFrom: "locations" as const },
  { key: "categoryId", label: "Category", type: "select" as const, optionsFrom: "categories" as const },
  { key: "brandId", label: "Brand", type: "select" as const, optionsFrom: "brands" as const },
  { key: "productId", label: "Product", type: "select" as const, optionsFrom: "products" as const },
  { key: "sku", label: "SKU", type: "search" as const },
];

const BATCH_FILTERS = [
  ...PRODUCT_FILTERS,
  { key: "batchId", label: "Batch", type: "select" as const, optionsFrom: "batches" as const },
];

const MOVEMENT_FILTERS = [
  ...PRODUCT_FILTERS,
  { key: "movementType", label: "Type", type: "select" as const, optionsFrom: "movementType" as const },
  { key: "supplierId", label: "Supplier", type: "select" as const, optionsFrom: "suppliers" as const },
];

const STATUS_FILTERS = [
  ...PRODUCT_FILTERS,
  { key: "status", label: "Status", type: "select" as const, optionsFrom: "status" as const },
];

const PRODUCT_COLUMNS = [
  { key: "productName", label: "Product", type: "text" as const, sortable: true },
  { key: "sku", label: "SKU", type: "text" as const, sortable: true },
  { key: "unit", label: "Unit", type: "text" as const },
];

export const STOCK_REPORT_DEFINITIONS: ReportDefinition[] = [
  {
    id: "stock-summary",
    title: "Stock Summary",
    description: "Opening, inward, outward, adjustments and closing stock.",
    category: "position",
    filters: PRODUCT_FILTERS,
    columns: [
      ...PRODUCT_COLUMNS,
      { key: "opening", label: "Opening", type: "qty", align: "right", sortable: true },
      { key: "inward", label: "In", type: "qty", align: "right", sortable: true },
      { key: "outward", label: "Out", type: "qty", align: "right", sortable: true },
      { key: "positiveAdj", label: "+ Adj", type: "qty", align: "right" },
      { key: "negativeAdj", label: "- Adj", type: "qty", align: "right" },
      { key: "closing", label: "Closing", type: "qty", align: "right", sortable: true },
    ],
  },
  {
    id: "current-stock",
    title: "Current Stock",
    description: "On-hand quantity and stock value from the ledger.",
    category: "position",
    filters: STATUS_FILTERS,
    columns: [
      ...PRODUCT_COLUMNS,
      { key: "warehouse", label: "Warehouse", type: "text" },
      { key: "quantity", label: "Qty", type: "qty", align: "right", sortable: true },
      { key: "stockValue", label: "Value", type: "currency", align: "right", sortable: true },
      { key: "status", label: "Status", type: "status" },
    ],
  },
  {
    id: "low-stock",
    title: "Low Stock",
    description: "Items at or below the configured low-stock / min-stock level.",
    category: "position",
    filters: PRODUCT_FILTERS,
    columns: [
      ...PRODUCT_COLUMNS,
      { key: "quantity", label: "Qty", type: "qty", align: "right", sortable: true },
      { key: "threshold", label: "Threshold", type: "qty", align: "right" },
      { key: "shortage", label: "Shortage", type: "qty", align: "right", sortable: true },
      { key: "status", label: "Status", type: "status" },
    ],
  },
  {
    id: "out-of-stock",
    title: "Out of Stock",
    description: "Tracked products with zero on-hand quantity.",
    category: "position",
    filters: PRODUCT_FILTERS,
    columns: [
      ...PRODUCT_COLUMNS,
      { key: "quantity", label: "Qty", type: "qty", align: "right" },
      { key: "reorderLevel", label: "Reorder", type: "qty", align: "right" },
      { key: "status", label: "Status", type: "status" },
    ],
  },
  {
    id: "negative-stock",
    title: "Negative Stock",
    description: "Products whose ledger balance is below zero.",
    category: "position",
    filters: PRODUCT_FILTERS,
    columns: [
      ...PRODUCT_COLUMNS,
      { key: "quantity", label: "Qty", type: "qty", align: "right", sortable: true },
      { key: "status", label: "Status", type: "status" },
    ],
  },
  {
    id: "stock-ledger",
    title: "Stock Ledger",
    description: "Every stock movement in the selected period.",
    category: "movement",
    filters: MOVEMENT_FILTERS,
    columns: [
      { key: "date", label: "Date", type: "date", sortable: true },
      { key: "productName", label: "Product", type: "text", sortable: true },
      { key: "sku", label: "SKU", type: "text" },
      { key: "movementType", label: "Type", type: "status" },
      { key: "warehouse", label: "Warehouse", type: "text" },
      { key: "batchNo", label: "Batch", type: "text" },
      { key: "inQty", label: "In", type: "qty", align: "right" },
      { key: "outQty", label: "Out", type: "qty", align: "right" },
      { key: "balance", label: "Balance", type: "qty", align: "right" },
      { key: "reference", label: "Reference", type: "text" },
    ],
  },
  {
    id: "stock-in",
    title: "Stock In",
    description: "Purchases, sale returns, opening and inbound transfers.",
    category: "movement",
    filters: MOVEMENT_FILTERS,
    columns: [
      { key: "date", label: "Date", type: "date", sortable: true },
      { key: "productName", label: "Product", type: "text" },
      { key: "sku", label: "SKU", type: "text" },
      { key: "movementType", label: "Type", type: "status" },
      { key: "quantity", label: "Qty", type: "qty", align: "right", sortable: true },
      { key: "warehouse", label: "Warehouse", type: "text" },
      { key: "reference", label: "Reference", type: "text" },
    ],
  },
  {
    id: "stock-out",
    title: "Stock Out",
    description: "Sales, purchase returns, scrap and outbound transfers.",
    category: "movement",
    filters: MOVEMENT_FILTERS,
    columns: [
      { key: "date", label: "Date", type: "date", sortable: true },
      { key: "productName", label: "Product", type: "text" },
      { key: "sku", label: "SKU", type: "text" },
      { key: "movementType", label: "Type", type: "status" },
      { key: "quantity", label: "Qty", type: "qty", align: "right", sortable: true },
      { key: "warehouse", label: "Warehouse", type: "text" },
      { key: "reference", label: "Reference", type: "text" },
    ],
  },
  {
    id: "stock-adjustment",
    title: "Stock Adjustment",
    description: "Positive and negative adjustment entries.",
    category: "movement",
    filters: PRODUCT_FILTERS,
    columns: [
      { key: "date", label: "Date", type: "date", sortable: true },
      { key: "productName", label: "Product", type: "text" },
      { key: "sku", label: "SKU", type: "text" },
      { key: "quantity", label: "Change", type: "qty", align: "right", sortable: true },
      { key: "warehouse", label: "Warehouse", type: "text" },
      { key: "notes", label: "Notes", type: "text" },
    ],
  },
  {
    id: "stock-transfer",
    title: "Stock Transfer",
    description: "Transfer-in and transfer-out movements between warehouses.",
    category: "movement",
    filters: PRODUCT_FILTERS,
    columns: [
      { key: "date", label: "Date", type: "date", sortable: true },
      { key: "productName", label: "Product", type: "text" },
      { key: "sku", label: "SKU", type: "text" },
      { key: "movementType", label: "Type", type: "status" },
      { key: "quantity", label: "Qty", type: "qty", align: "right" },
      { key: "warehouse", label: "Warehouse", type: "text" },
      { key: "reference", label: "Reference", type: "text" },
    ],
  },
  {
    id: "purchase-return-stock",
    title: "Purchase Return Stock",
    description: "Stock removed through purchase returns.",
    category: "movement",
    filters: [...PRODUCT_FILTERS, { key: "supplierId", label: "Supplier", type: "select", optionsFrom: "suppliers" }],
    columns: [
      { key: "date", label: "Date", type: "date", sortable: true },
      { key: "productName", label: "Product", type: "text" },
      { key: "sku", label: "SKU", type: "text" },
      { key: "quantity", label: "Qty", type: "qty", align: "right", sortable: true },
      { key: "warehouse", label: "Warehouse", type: "text" },
      { key: "reference", label: "Reference", type: "text" },
    ],
  },
  {
    id: "sales-return-stock",
    title: "Sales Return Stock",
    description: "Stock restored through sales returns.",
    category: "movement",
    filters: PRODUCT_FILTERS,
    columns: [
      { key: "date", label: "Date", type: "date", sortable: true },
      { key: "productName", label: "Product", type: "text" },
      { key: "sku", label: "SKU", type: "text" },
      { key: "quantity", label: "Qty", type: "qty", align: "right", sortable: true },
      { key: "warehouse", label: "Warehouse", type: "text" },
      { key: "reference", label: "Reference", type: "text" },
    ],
  },
  {
    id: "fast-moving",
    title: "Fast Moving",
    description: "Products sold at or above the fast-moving threshold.",
    category: "analysis",
    filters: PRODUCT_FILTERS,
    columns: [
      ...PRODUCT_COLUMNS,
      { key: "soldQty", label: "Sold", type: "qty", align: "right", sortable: true },
      { key: "closing", label: "On hand", type: "qty", align: "right" },
      { key: "band", label: "Band", type: "status" },
    ],
  },
  {
    id: "slow-moving",
    title: "Slow Moving",
    description: "Products with some sales below the fast-moving threshold.",
    category: "analysis",
    filters: PRODUCT_FILTERS,
    columns: [
      ...PRODUCT_COLUMNS,
      { key: "soldQty", label: "Sold", type: "qty", align: "right", sortable: true },
      { key: "closing", label: "On hand", type: "qty", align: "right" },
      { key: "band", label: "Band", type: "status" },
    ],
  },
  {
    id: "non-moving",
    title: "Non Moving / Dead Stock",
    description: "On-hand items with no sales in the selected period.",
    category: "analysis",
    filters: PRODUCT_FILTERS,
    columns: [
      ...PRODUCT_COLUMNS,
      { key: "soldQty", label: "Sold", type: "qty", align: "right" },
      { key: "closing", label: "On hand", type: "qty", align: "right", sortable: true },
      { key: "lastMovement", label: "Last movement", type: "date" },
      { key: "band", label: "Band", type: "status" },
    ],
  },
  {
    id: "stock-aging",
    title: "Stock Aging",
    description: "On-hand quantity by days since last inbound receipt.",
    category: "analysis",
    filters: PRODUCT_FILTERS,
    columns: [
      ...PRODUCT_COLUMNS,
      { key: "quantity", label: "Qty", type: "qty", align: "right", sortable: true },
      { key: "days", label: "Days", type: "number", align: "right", sortable: true },
      { key: "bucket", label: "Bucket", type: "status" },
      { key: "stockValue", label: "Value", type: "currency", align: "right" },
    ],
  },
  {
    id: "abc-analysis",
    title: "ABC Analysis",
    description: "Products ranked by stock value (A 80%, B 15%, C 5%).",
    category: "analysis",
    filters: PRODUCT_FILTERS,
    columns: [
      ...PRODUCT_COLUMNS,
      { key: "quantity", label: "Qty", type: "qty", align: "right" },
      { key: "stockValue", label: "Value", type: "currency", align: "right", sortable: true },
      { key: "share", label: "Share %", type: "number", align: "right" },
      { key: "class", label: "Class", type: "status" },
    ],
  },
  {
    id: "stock-valuation",
    title: "Stock Valuation",
    description: "On-hand quantity valued at purchase cost.",
    category: "valuation",
    filters: PRODUCT_FILTERS,
    columns: [
      ...PRODUCT_COLUMNS,
      { key: "quantity", label: "Qty", type: "qty", align: "right", sortable: true },
      { key: "costPrice", label: "Cost", type: "currency", align: "right" },
      { key: "stockValue", label: "Value", type: "currency", align: "right", sortable: true },
    ],
  },
  {
    id: "batch-wise-stock",
    title: "Batch-wise Stock",
    description: "On-hand quantity by batch. Batch identifies stock, never quantity.",
    category: "batch",
    filters: BATCH_FILTERS,
    columns: [
      ...PRODUCT_COLUMNS,
      { key: "batchNo", label: "Batch", type: "text", sortable: true },
      { key: "expiryDate", label: "Expiry", type: "date", sortable: true },
      { key: "warehouse", label: "Warehouse", type: "text" },
      { key: "quantity", label: "Qty", type: "qty", align: "right", sortable: true },
      { key: "mrp", label: "MRP", type: "currency", align: "right" },
    ],
  },
  {
    id: "expiry-stock",
    title: "Expiry Stock",
    description: "Batches that have expired or expire within the near-expiry window.",
    category: "batch",
    filters: BATCH_FILTERS,
    columns: [
      ...PRODUCT_COLUMNS,
      { key: "batchNo", label: "Batch", type: "text" },
      { key: "expiryDate", label: "Expiry", type: "date", sortable: true },
      { key: "daysToExpiry", label: "Days", type: "number", align: "right", sortable: true },
      { key: "quantity", label: "Qty", type: "qty", align: "right" },
      { key: "status", label: "Status", type: "status" },
    ],
  },
  {
    id: "warehouse-stock",
    title: "Warehouse-wise Stock",
    description: "On-hand quantity grouped by warehouse.",
    category: "warehouse",
    filters: PRODUCT_FILTERS,
    columns: [
      { key: "warehouse", label: "Warehouse", type: "text", sortable: true },
      { key: "productName", label: "Product", type: "text", sortable: true },
      { key: "sku", label: "SKU", type: "text" },
      { key: "quantity", label: "Qty", type: "qty", align: "right", sortable: true },
      { key: "stockValue", label: "Value", type: "currency", align: "right" },
    ],
  },
  {
    id: "location-stock",
    title: "Location-wise Stock",
    description: "On-hand quantity grouped by stock location.",
    category: "warehouse",
    filters: PRODUCT_FILTERS,
    columns: [
      { key: "warehouse", label: "Warehouse", type: "text" },
      { key: "location", label: "Location", type: "text", sortable: true },
      { key: "productName", label: "Product", type: "text", sortable: true },
      { key: "sku", label: "SKU", type: "text" },
      { key: "quantity", label: "Qty", type: "qty", align: "right", sortable: true },
    ],
  },
  {
    id: "unused-stock",
    title: "Unused Stock",
    description: "On-hand items with no ledger activity in the selected period.",
    category: "control",
    filters: PRODUCT_FILTERS,
    columns: [
      ...PRODUCT_COLUMNS,
      { key: "quantity", label: "Qty", type: "qty", align: "right", sortable: true },
      { key: "lastMovement", label: "Last movement", type: "date" },
      { key: "stockValue", label: "Value", type: "currency", align: "right" },
    ],
  },
  {
    id: "stock-mismatch",
    title: "Stock Mismatch",
    description: "Products whose closing quantity does not match summed ledger movements.",
    category: "control",
    filters: PRODUCT_FILTERS,
    columns: [
      ...PRODUCT_COLUMNS,
      { key: "ledgerQty", label: "Ledger", type: "qty", align: "right" },
      { key: "closing", label: "Closing", type: "qty", align: "right" },
      { key: "difference", label: "Difference", type: "qty", align: "right", sortable: true },
    ],
  },
];

export const STOCK_REPORT_CATEGORIES: { id: StockReportCategory; label: string }[] = [
  { id: "position", label: "Stock position" },
  { id: "movement", label: "Stock movement" },
  { id: "analysis", label: "Stock analysis" },
  { id: "valuation", label: "Valuation" },
  { id: "batch", label: "Batch & expiry" },
  { id: "warehouse", label: "Warehouse" },
  { id: "control", label: "Stock control" },
];

export function getStockReportDefinition(id: string): ReportDefinition | undefined {
  return STOCK_REPORT_DEFINITIONS.find((definition) => definition.id === id);
}

export function listStockReportsByCategory(category: StockReportCategory): ReportDefinition[] {
  return STOCK_REPORT_DEFINITIONS.filter((definition) => definition.category === category);
}
